const double PORTRAIT_HEIGHT_BODY_RATIO = 1.3;
const double PORTRAIT_HEIGHT_FOOTER = 3;

const double LANDSCAPE_HEIGHT_BODY_RATIO = 1.1;
const double LANDSCAPE_HEIGHT_FOOTER = 3;
const double LANDSCAPE_WIDTH_PIXED = 500;
const double LANDSCAPE_WIDTH_RATIO = 0.95;

const double LANDSCAPE_DIALOG_WIDTH = 400;
const double LANDSCAPE_DIALOG_HEIGHT_RATIO = 0.4;
const double PORTRAIT_DIALOG_WIDTH_RATIO = 0.4;
const double PORTRAIT_DIALOG_HEIGHT_RATIO = 0.6;
